[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Neural-Operators"
authors = [
    { name = "Jakob Wagner", email = "mail@jakob-wagner.org" },
]
description = "Use Neural Operators for parameterized sonic crystals"
readme = "README.md"
requires-python = ">=3.11"
keywords = [
    "Artificial Intelligence",
    "Mathematics",
    "Physics",
    "Neural Operators",
    "Helmholtz",
    "Sonic Crystal",
]
license = { file = "LICENSE" }
classifiers = [
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Engineering",
    "Development Status :: 3 - Alpha",
]
dependencies = [
    "numpy",
]

version = "0.0.0"

[project.optional-dependencies]
dev = [
    # --------- style --------- #
    "black",
    "ruff",
    "isort",
    # --------- linters --------- #
    "pre-commit", # hooks for applying linters on commit
]
test = [
    "pytest",
    "pytest-cov",
]

[project.scripts]

[tool.black]
line-length = 119

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 119
skip_glob = [
    ".github/*",
    ".idea/*",
    ".pytest_cache/*",
    "data/*",
    "doc/*",
    "models/*",
    "venv/*",
]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 119
indent-width = 4
