defaults:
  - _self_
  - trainer: default
  - optim: default
  - lr_scheduler: default

training:
  epochs: 1000
  batch_size: 16

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +benchmark: transmission_loss_fno
      +operator: fourier_small, fourier_medium, fourier_big
