defaults:
  - _self_
  - trainer: default

training:
  epochs: 1000
  batch_size: 8

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +benchmark: transmission_loss_full
      +operator: mean_stack_small, deep_dot_small
