defaults:
  - _self_
  - trainer: default
  - optim: default
  - lr_scheduler: default

training:
  epochs: 1000
  batch_size: 12

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +benchmark: transmission_loss_smooth
      +operator: deep_dot_small, deep_neural_small, deep_o_small, deep_dot_medium, deep_neural_medium, deep_o_medium
