defaults:
  - _self_
  - trainer: default

training:
  epochs: 1000
  batch_size: 16

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +benchmark: transmission_loss_lin
      +operator: fourier_small
